@extends('layouts.candidate')
@section('content')
<div class="container">
    <h2>Exam Instructions</h2>
    <div class="card p-3">
        <ul>
            <li>The timer has been set for the exam. When it runs out, the exam ends automatically.</li>
            <li>You can flag any question.</li>
            <li>You can clear any answer you don’t want to submit.</li>
            <li>If you drop the exam, it will not be submitted or scored.</li>
            <li>Once you finish the exam, you cannot resume it.</li>
        </ul>

        <div class="form-check mt-3">
            <input class="form-check-input" type="checkbox" id="confirm" onchange="document.getElementById('startBtn').disabled = !this.checked;">
            <label class="form-check-label" for="confirm">
                I have read and understood the instructions. I agree to accept the results generated by this system.
            </label>
        </div>

        <div class="mt-4">
            <a href="{{ route('candidates.exam.start', $exam->id) }}" class="btn btn-success btn-lg" id="startBtn" disabled>Start Exam</a>
            <a href=" " class="btn btn-secondary btn-lg">Cancel</a>
        </div>
    </div>
</div>
@endsection
